import { useMemo, useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Copy, Download, ExternalLink, FileCode2, Moon, Search, ShieldCheck, Sun, Tv, Smartphone, Wifi, Wrench } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";
import { toast } from "sonner";

const categories = [{ id: "all", label: "الكل" }, { id: "smart-tv", label: "Smart TV" }, { id: "android-mobile", label: "Android Mobile" }, { id: "live-iptv", label: "Live IPTV" }, { id: "free-codes", label: "Free Codes" }];
const labels: Record<string, string> = { "smart-tv": "Smart TV", "android-mobile": "Android Mobile", "live-iptv": "Live IPTV", "free-codes": "Free Codes" };
const icons = { "smart-tv": Tv, "android-mobile": Smartphone, "live-iptv": Wifi, "free-codes": FileCode2 } as Record<string, typeof Tv>;

function parse<T>(value: string | null | undefined, fallback: T): T { try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } }

export default function Home() {
  const { theme, toggleTheme } = useTheme();
  const { data: apps = [], isLoading } = trpc.apps.publicList.useQuery();
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [selected, setSelected] = useState<any>(null);
  const filtered = useMemo(() => apps.filter(app => (category === "all" || app.category === category) && `${app.title} ${app.shortDescription}`.toLowerCase().includes(query.toLowerCase())), [apps, category, query]);
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); toast.success("تم نسخ الكود إلى الحافظة"); } catch { toast.error("تعذر النسخ تلقائيًا؛ حدّد الكود وانسخه يدويًا"); } };
  return <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="container relative z-10 flex items-center justify-between py-6">
      <Link href="/" className="flex items-center gap-3"><div className="brand-mark"><Tv className="h-5 w-5" /></div><div><div className="font-display text-lg md:text-xl font-bold tracking-tight">برامج <span className="text-primary">مشاهدة التلفاز مجانية</span></div><div className="text-[10px] uppercase tracking-[0.24em] text-muted-foreground">مكتبة تطبيقات البث</div></div></Link>
      <div className="flex items-center gap-2"><Link href="/admin"><Button variant="ghost" className="hidden sm:flex gap-2"><ShieldCheck className="h-4 w-4" /> لوحة الإدارة</Button></Link><Button size="icon" variant="outline" onClick={toggleTheme} aria-label="تبديل المظهر">{theme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}</Button></div>
    </header>
    <main className="container relative z-10 pb-20">
      <section className="hero-grid py-12 md:py-20"><div className="max-w-2xl"><Badge className="mb-6 rounded-full px-3 py-1 text-xs bg-primary/10 text-primary border-primary/20">مكتبة البث الذكية</Badge><h1 className="font-display text-5xl md:text-7xl font-bold tracking-tight leading-[.98]">تطبيقات مشاهدة التلفاز مجانية<br /><span className="gradient-text">علي الشاشة والهواتف اندرويد</span></h1><p className="mt-6 max-w-xl text-base md:text-lg text-muted-foreground leading-relaxed">مركز منظم لتطبيقات التلفاز وAndroid وأكواد التشغيل. كل ما تحتاجه للبدء، في مكان واحد وبخطوات واضحة.</p></div><div className="hero-orbit hidden lg:block"><div className="orbit-card orbit-card-main"><Tv className="h-8 w-8 text-primary" /><span>جاهز لشاشتك</span></div><div className="orbit-card orbit-card-small"><Wifi className="h-5 w-5 text-cyan-400" /><span>بث مباشر</span></div><div className="orbit-ring" /></div></section>
      <section className="toolbar sticky top-3 z-20 rounded-2xl p-3 md:p-4"><div className="relative flex-1"><Search className="absolute right-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث عن تطبيق أو ميزة..." className="h-12 rounded-xl border-border/60 bg-background/70 pr-11" /></div><div className="category-scroll flex gap-2 mt-3 overflow-x-auto pb-1">{categories.map(item => <Button key={item.id} onClick={() => setCategory(item.id)} variant={category === item.id ? "default" : "outline"} className="shrink-0 rounded-xl">{item.label}</Button>)}</div></section>
      <div className="mt-12 flex items-end justify-between"><div><p className="eyebrow">المكتبة</p><h2 className="font-display text-2xl md:text-3xl font-bold">تطبيقات مختارة</h2></div><span className="text-sm text-muted-foreground">{filtered.length} تطبيق</span></div>
      {isLoading ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-6">{[1,2,3].map(i => <div key={i} className="skeleton-card h-72 rounded-2xl" />)}</div> : <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-6">{filtered.map((app, index) => { const Icon = icons[app.category] || Wrench; const compatibility = parse<string[]>(app.compatibility, []); return <article key={app.id} className="app-card group" style={{ animationDelay: `${index * 45}ms` }} onClick={() => setSelected(app)}><div className="app-cover" style={app.coverUrl ? { backgroundImage: `linear-gradient(180deg, transparent, hsl(var(--card))), url(${app.coverUrl})` } : undefined}><div className="app-icon">{app.iconUrl ? <img src={app.iconUrl} alt="" /> : <Icon className="h-7 w-7 text-primary" />}</div><Badge className="absolute top-4 left-4 bg-background/80 backdrop-blur border-border/50">{labels[app.category]}</Badge></div><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-display text-xl font-semibold">{app.title}</h3><p className="mt-2 text-sm text-muted-foreground line-clamp-2">{app.shortDescription}</p></div><span className="text-xs text-muted-foreground whitespace-nowrap">v{app.version}</span></div><div className="mt-5 flex flex-wrap gap-2">{compatibility.map(item => <span key={item} className="compat-chip">{item}</span>)}</div><div className="mt-5 flex items-center justify-between text-sm"><span className="text-muted-foreground">{app.fileSize}</span><span className="text-primary font-medium group-hover:translate-x-[-3px] transition-transform">التفاصيل ←</span></div></div></article> })}</div>}
      {!isLoading && filtered.length === 0 && <div className="empty-state mt-6"><Search className="h-8 w-8 text-muted-foreground" /><p className="font-medium mt-3">لم نجد نتائج مطابقة</p><p className="text-sm text-muted-foreground mt-1">جرّب كلمة بحث مختلفة أو غيّر الفئة.</p></div>}
    </main>
    <Dialog open={!!selected} onOpenChange={open => !open && setSelected(null)}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle className="font-display text-3xl">{selected?.title}</DialogTitle></DialogHeader>{selected && <div className="space-y-6"><p className="text-muted-foreground leading-relaxed">{selected.description}</p><div><p className="eyebrow mb-3">أكواد التفعيل</p><div className="space-y-2">{parse<{title:string,value:string}[]>(selected.activationCodes, []).map((code, i) => <div className="code-row" key={i}><div><div className="text-sm font-medium">{code.title}</div><code className="text-primary text-sm">{code.value}</code></div><Button size="sm" variant="outline" onClick={() => copy(code.value)}><Copy className="h-4 w-4 ml-2" />نسخ</Button></div>)}</div></div><div><p className="eyebrow mb-3">التثبيت</p><ol className="space-y-2">{parse<string[]>(selected.installationSteps, []).map((step, i) => <li key={i} className="flex gap-3 text-sm text-muted-foreground"><span className="step-number">{i + 1}</span>{step}</li>)}</ol></div><div className="flex flex-wrap gap-3"><Button asChild disabled={!selected.apkUrl}><a href={selected.apkUrl || "#"} target="_blank" rel="noreferrer"><Download className="h-4 w-4 ml-2" />تحميل APK</a></Button>{selected.mirrorUrl && <Button asChild variant="outline"><a href={selected.mirrorUrl} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4 ml-2" />رابط بديل</a></Button>}</div></div>}</DialogContent></Dialog>
  </div>;
}
